apiVersion: v1
kind: ServiceAccount
metadata:
  name: sqs-processor
  namespace: sqs-processor
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/sqs-processor-role  # Replace ACCOUNT_ID with your AWS account ID
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sqs-processor
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sqs-processor
subjects:
  - kind: ServiceAccount
    name: sqs-processor
    namespace: sqs-processor
roleRef:
  kind: ClusterRole
  name: sqs-processor
  apiGroup: rbac.authorization.k8s.io
