apiVersion: v1
kind: ConfigMap
metadata:
  name: email-processor-config
  namespace: email-processor
data:
  sqs_queue_url: "https://sqs.us-west-1.amazonaws.com/ACCOUNT_ID/dev-CP-queue"
  aws_region: "us-west-1"
